### ISSUE TITLE
能否不强依赖 'easywebpack-react'

### ISSUE THREAD

**Issue by ghost** [hubcarl/egg-webpack#8]
能否不强依赖 'easywebpack-react'.
安装完毕, 跑以下命令
npm run tsc:w & node index.js
提示
```
ERROR 30743 nodejs.unhandledExceptionError: Cannot find module 'easywebpack-react'
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
```

**Comment by ghost** [comment]
是我自己问题. 只需要配置
```
exports.webpack = {
        webpackConfigList: [require('../webpack.config.js')],
      };
```
